// test-gr6.js — Grammatik: Passiv alle Formen
window.TELC_TEST = {
  id:"gr6", type:"Grammatik", kind:"gr",
  title:"Passiv: Vorgangspassiv · Zustandspassiv · Modalpassiv",
  desc:"10 Aufgaben · Passivkonstruktionen · C1",
  qs:[
    {n:1,
     aufgabe:"Aktiv → Passiv: «Man baut die Brücke.» → Vorgangspassiv Präsens:",
     opts:["a) Die Brücke ist gebaut.",
           "b) Die Brücke wird gebaut.",
           "c) Die Brücke wurde gebaut.",
           "d) Die Brücke ist gebaut worden."],
     ans:"b) Die Brücke wird gebaut.",
     exp:"<strong>Vorgangspassiv Präsens</strong>: wird + Partizip II. «Die Brücke <em>wird</em> gebaut.» = мост строится (процесс). <em>ist gebaut</em> = Zustandspassiv (мост уже построен, состояние).",
     rule:"VORGANGSPASSIV: werden + Part.II (Prozess). ZUSTANDSPASSIV: sein + Part.II (Ergebnis/Zustand)."},
    {n:2,
     aufgabe:"«Die Brücke ___ gestern fertiggestellt ___» — Vorgangspassiv Präteritum:",
     opts:["a) ist … worden","b) wurde … worden","c) wurde … fertiggestellt","d) war … fertiggestellt"],
     ans:"c) wurde … fertiggestellt",
     exp:"<strong>Vorgangspassiv Präteritum</strong>: wurde + Partizip II. «Die Brücke <em>wurde</em> gestern fertiggestellt.» — kein <em>worden</em> am Ende beim Präteritum! <em>worden</em> nur im Perfekt: «ist … worden».",
     rule:"VORGANGSPASSIV: Präsens: wird + P.II | Präteritum: wurde + P.II | Perfekt: ist + P.II + worden."},
    {n:3,
     aufgabe:"Zustandspassiv: «Die Tür ___ .» (Sie haben sie schon geschlossen.)",
     opts:["a) wird geschlossen","b) wurde geschlossen","c) ist geschlossen","d) ist geschlossen worden"],
     ans:"c) ist geschlossen",
     exp:"<strong>Zustandspassiv</strong>: sein + Partizip II = результат/состояние. «Die Tür <em>ist geschlossen</em>.» = дверь закрыта (состояние). «Die Tür <em>wird geschlossen</em>» = дверь закрывают (процесс).",
     rule:"ZUSTANDSPASSIV: sein + Part.II (Zustand, кто-то уже сделал). ≠ Vorgangspassiv: werden + Part.II."},
    {n:4,
     aufgabe:"Modalpassiv: «Man kann das Problem lösen.» → Passiv:",
     opts:["a) Das Problem kann gelöst sein.",
           "b) Das Problem kann gelöst werden.",
           "c) Das Problem lässt sich gelöst werden.",
           "d) Das Problem wird gelöst können."],
     ans:"b) Das Problem kann gelöst werden.",
     exp:"<strong>Modalpassiv</strong>: Modalverb + Partizip II + werden. «Das Problem <em>kann</em> gelöst <em>werden</em>.» = проблему можно решить. Im Nebensatz: «…, dass das Problem gelöst werden kann.»",
     rule:"MODALPASSIV: Modal + Part.II + werden. Hauptsatz: Modal an Pos.2, werden am Ende."},
    {n:5,
     aufgabe:"Passiv-Ersatz: «Das Fenster lässt sich öffnen.» bedeutet:",
     opts:["a) Das Fenster wird geöffnet.",
           "b) Das Fenster kann geöffnet werden.",
           "c) Das Fenster ist geöffnet worden.",
           "d) Das Fenster muss geöffnet werden."],
     ans:"b) Das Fenster kann geöffnet werden.",
     exp:"<strong>lassen sich + Infinitiv</strong> = можно сделать = können + Passiv. «Das Fenster <em>lässt sich öffnen</em>» = Das Fenster kann geöffnet werden. Sehr häufige C1-Konstruktion!",
     rule:"LASSEN SICH + Inf. = können + Passiv (можно). Das lässt sich nicht ändern = нельзя изменить."},
    {n:6,
     aufgabe:"«Hier ___ nicht geraucht ___» — Passiv ohne Subjekt (unpersönlich):",
     opts:["a) ist … werden","b) wird … —","c) werden … —","d) ist … worden"],
     ans:"b) wird … —",
     exp:"<strong>Unpersönliches Passiv</strong>: kein Subjekt → «Hier <em>wird</em> nicht geraucht.» (= здесь не курят). Das Verb steht an Pos.1 oder nach Adverb. Kein <em>es</em> nötig bei Adverb am Anfang.",
     rule:"UNPERSÖNL. PASSIV: Hier wird gearbeitet. Auf der Straße wird demonstriert. Kein Agens nötig."},
    {n:7,
     aufgabe:"Perfekt Passiv: «Das Gebäude ___ renoviert ___» (abgeschlossene Handlung)",
     opts:["a) wurde … worden","b) ist … worden","c) ist … geworden","d) war … worden"],
     ans:"b) ist … worden",
     exp:"<strong>Perfekt Passiv</strong>: ist + Partizip II + worden. «Das Gebäude <em>ist</em> renoviert <em>worden</em>.» = здание было отремонтировано (результат в настоящем). <em>worden</em> ≠ <em>geworden</em> (werden = стать).",
     rule:"PERFEKT PASSIV: ist + Part.II + worden. NICHT: geworden! (geworden = Passiv von werden = стать)"},
    {n:8,
     aufgabe:"«Das Haus ___ fertig gebaut worden ___ .» — Plusquamperfekt Passiv:",
     opts:["a) ist … sein","b) war … —","c) war … sein","d) wurde … —"],
     ans:"b) war … —",
     exp:"<strong>Plusquamperfekt Passiv</strong>: war + Partizip II + worden. «Das Haus <em>war</em> fertig gebaut <em>worden</em>.» = дом был построен (до другого события в прошлом). war, nicht ist!",
     rule:"PLUSQUAMPERFEKT PASSIV: war + Part.II + worden (до другого события в прошлом)."},
    {n:9,
     aufgabe:"«Das hätte vermieden werden ___» — Konj.II Perfekt Passiv:",
     opts:["a) sollen","b) können","c) müssen","d) können oder sollen (je nach Kontext)"],
     ans:"d) können oder sollen (je nach Kontext)",
     exp:"<em>hätte vermieden werden können</em> = можно было бы предотвратить (возможность). <em>hätte vermieden werden sollen</em> = следовало бы предотвратить (долженствование). Beide korrekt — je nach Aussageabsicht.",
     rule:"KONJ.II PASSIV + MODAL PERFEKT: hätte + Part.II + werden + Modal (können/sollen/müssen)."},
    {n:10,
     aufgabe:"Welcher Passivtyp ist das? «Nach der Sitzung war der Beschluss gefasst.»",
     opts:["a) Vorgangspassiv Präteritum","b) Zustandspassiv Präteritum","c) Perfekt Passiv","d) Unpersönliches Passiv"],
     ans:"b) Zustandspassiv Präteritum",
     exp:"<strong>Zustandspassiv Präteritum</strong>: war + Partizip II. «Der Beschluss <em>war</em> gefasst.» = решение было принято (состояние в прошлом). Не процесс, а результат — поэтому Zustandspassiv, не Vorgangspassiv.",
     rule:"ZUSTANDSPASSIV: Präsens: ist + P.II | Präteritum: war + P.II | ≠ Vorgangspassiv (werden)."}
  ],
  vocab:["Vorgangspassiv — пассив процесса (werden + P.II)","Zustandspassiv — пассив состояния (sein + P.II)","Modalpassiv — пассив с модальным глаголом","worden — причастие II от werden (в пассиве)","lassen sich + Inf. — можно (пассивная замена)","unpersönliches Passiv — безличный пассив","Plusquamperfekt Passiv — пассив предпрошедшего (war + P.II + worden)"]
};
