// test-gr10.js — Grammatik: Konnektoren des formellen Textes
window.TELC_TEST = {
  id:"gr10", type:"Grammatik", kind:"gr",
  title:"Konnektoren des formellen Textes: demzufolge · gleichwohl · zumal",
  desc:"10 Aufgaben · Formelle Konnektoren · C1",
  qs:[
    {n:1,
     aufgabe:"«Die Studie zeigte klare Ergebnisse. ___ wurden weitere Maßnahmen eingeleitet.» Formeller Konnektor für «deshalb»:",
     opts:["a) Dennoch","b) Demzufolge","c) Gleichwohl","d) Infolgedessen"],
     ans:"d) Infolgedessen",
     exp:"<strong>infolgedessen</strong> = вследствие этого, поэтому (formal). «…zeigt klare Ergebnisse. <em>Infolgedessen</em> wurden Maßnahmen eingeleitet.» Steht an Pos.1, Verb an Pos.2. Synonym: daher, deshalb, demzufolge.",
     rule:"INFOLGEDESSEN = вследствие этого (formal = deshalb/daher). Pos.1 → Verb Pos.2."},
    {n:2,
     aufgabe:"«___ wurden keine Beweise gefunden. Dennoch bleibt er verdächtig.» Was bedeutet <em>demzufolge</em>?",
     opts:["a) тем не менее","b) следовательно, вследствие этого","c) несмотря на это","d) кроме того"],
     ans:"b) следовательно, вследствие этого",
     exp:"<strong>demzufolge</strong> = следовательно, таким образом (= daher, folglich). Leitet Schlussfolgerung ein. «Die Daten sind eindeutig. <em>Demzufolge</em> muss gehandelt werden.» Hochformeller Stil.",
     rule:"DEMZUFOLGE = следовательно, таким образом (sehr formal). Синонимы: folglich, daher, demnach."},
    {n:3,
     aufgabe:"«Das Ergebnis war enttäuschend. ___ setzte das Team seine Arbeit fort.» Konnektor für «trotzdem» formal:",
     opts:["a) Demzufolge","b) Infolgedessen","c) Gleichwohl","d) Zumal"],
     ans:"c) Gleichwohl",
     exp:"<strong>gleichwohl</strong> = тем не менее (= trotzdem, dennoch, высокий стиль). «Das Ergebnis war enttäuschend. <em>Gleichwohl</em> setzte das Team seine Arbeit fort.» Концессивный коннектор главного предложения.",
     rule:"GLEICHWOHL = тем не менее (formal = trotzdem). Главное предложение, Pos.1."},
    {n:4,
     aufgabe:"«Das Projekt ist wichtig, ___ es auch teuer ist.» — Konzessiv im Nebensatz (formal):",
     opts:["a) obwohl","b) wenngleich","c) gleichwohl","d) zumal"],
     ans:"b) wenngleich",
     exp:"<strong>wenngleich</strong> = хотя (= obwohl, книжный стиль). Leitet Nebensatz ein (Verb am Ende). «Das Projekt ist wichtig, <em>wenngleich</em> es auch teuer ist.» <em>gleichwohl</em> leitet Hauptsätze ein, nicht Nebensätze.",
     rule:"WENNGLEICH = obwohl (Nebensatz, формальный). GLEICHWOHL = trotzdem (Hauptsatz)."},
    {n:5,
     aufgabe:"«Das Verfahren ist aufwendig, ___ es sich um einen komplexen Fall handelt.» — Kausal, verstärkend:",
     opts:["a) sodass","b) zumal","c) wohingegen","d) demzufolge"],
     ans:"b) zumal",
     exp:"<strong>zumal</strong> = тем более что; особенно (поскольку). «Das Verfahren ist aufwendig, <em>zumal</em> es sich um einen komplexen Fall handelt.» = тем более что речь идёт о сложном деле. Fügt eine verstärkende Begründung hinzu.",
     rule:"ZUMAL (DA) = тем более что; особенно учитывая, что. Verstärkende Kausalangabe. C1!"},
    {n:6,
     aufgabe:"«___ dem oben Gesagten ergibt sich folgende Schlussfolgerung.» — Logische Herleitung:",
     opts:["a) Demzufolge","b) Aus","c) Infolge","d) Demnach"],
     ans:"b) Aus",
     exp:"<strong>Aus + Dativ + ergibt sich</strong> = из этого следует. «<em>Aus</em> dem oben Gesagten ergibt sich…» Typische Formulierung in wissenschaftlichen Texten und Stellungnahmen (C1). Präposition, kein Konnektor.",
     rule:"AUS + Dat. + ERGIBT SICH = из … следует. Wissenschaftliche Schlussfolgerung."},
    {n:7,
     aufgabe:"«___ man berücksichtigt, dass … , zeigt sich, dass …» — Konditional-Final formal:",
     opts:["a) Berücksichtigt","b) Wenn man","c) Zieht man in Betracht, dass","d) Sowohl b) als auch c)"],
     ans:"d) Sowohl b) als auch c)",
     exp:"Beide sind korrekt. <em>Wenn man berücksichtigt, dass</em> = если учитывать, что (нейтрально). <em>Zieht man in Betracht, dass</em> = принимая во внимание, что (высокий стиль, инверсия). Beide typisch für C1-Argumentationstexte.",
     rule:"ZIEHT MAN IN BETRACHT, DASS = принимая во внимание, что (инверсия, формальный стиль)."},
    {n:8,
     aufgabe:"«___ lässt sich festhalten, dass die Maßnahmen wirksam waren.» — Zusammenfassung:",
     opts:["a) Abschließend","b) Zusammenfassend","c) Festzuhalten ist: beides korrekt","d) Sowohl a) als auch b)"],
     ans:"d) Sowohl a) als auch b)",
     exp:"<em>Abschließend</em> = в заключение. <em>Zusammenfassend</em> = подводя итог. Beide einleiten Schlussfolgerungen. Weitere C1-Varianten: «Im Ergebnis lässt sich sagen, dass…», «Insgesamt ist festzustellen, dass…»",
     rule:"ZUSAMMENFASSEND / ABSCHLIEßEND lässt sich sagen, dass = подводя итог / в заключение."},
    {n:9,
     aufgabe:"Welcher Ausdruck leitet in formellen Texten eine EINSCHRÄNKUNG ein?",
     opts:["a) demzufolge","b) infolgedessen","c) allerdings","d) zumal"],
     ans:"c) allerdings",
     exp:"<strong>allerdings</strong> = однако, тем не менее (Einschränkung/Gegenargument). «Das Projekt war erfolgreich. <em>Allerdings</em> überschritt es das Budget.» Achtung: <em>allerdings</em> = jedoch (Einschränkung), nicht = selbstverständlich (umg.).",
     rule:"ALLERDINGS = однако (Einschränkung, Hauptsatz Pos.1). ≠ demzufolge (Schlussfolgerung)."},
    {n:10,
     aufgabe:"Ordne zu: «___ des Gesagten / ___ dieses Ergebnisses / ___ der Umstände» — Präpositionen formal:",
     opts:["a) Aufgrund / Angesichts / Trotz","b) Infolge / Trotz / Angesichts","c) Trotz / Aufgrund / Infolge","d) Angesichts / Aufgrund / Infolge"],
     ans:"a) Aufgrund / Angesichts / Trotz",
     exp:"<em>aufgrund des Gesagten</em> = вследствие / ввиду сказанного. <em>angesichts dieses Ergebnisses</em> = ввиду этого результата. <em>trotz der Umstände</em> = несмотря на обстоятельства. Alle + Genitiv.",
     rule:"AUFGRUND (вследствие), ANGESICHTs (ввиду), TROTZ (несмотря на) + Genitiv. C1-Präpositionen!"}
  ],
  vocab:["demzufolge — следовательно (очень формально)","infolgedessen — вследствие этого","gleichwohl — тем не менее (Hauptsatz, формально)","wenngleich — хотя (Nebensatz, формально)","zumal (da) — тем более что","allerdings — однако (ограничение)","abschließend — в заключение","zusammenfassend — подводя итог","aufgrund + Gen. — вследствие","angesichts + Gen. — ввиду","trotz + Gen. — несмотря на"]
};
