// test-gr3.js — Grammatik: Konsekutiv & Konditional
window.TELC_TEST = {
  id:"gr3", type:"Grammatik", kind:"gr",
  title:"Konsekutivsatz & Konditionalsatz: sodass · sofern · es sei denn",
  desc:"10 Aufgaben · Folge & Bedingung · C1",
  qs:[
    {n:1,
     aufgabe:"«Er sprach so leise, ___ ihn niemand verstehen konnte.» Welcher Konnektor?",
     opts:["a) sodass","b) damit","c) indem","d) obwohl"],
     ans:"a) sodass",
     exp:"<strong>sodass</strong> — консекутивное придаточное (следствие). «Er sprach so leise, <em>sodass</em> ihn niemand verstehen konnte.» = он говорил так тихо, что его никто не мог понять. Сигнал: so/solch + … sodass.",
     rule:"SODASS = так что (следствие). Часто с so…sodass или derart…sodass."},
    {n:2,
     aufgabe:"Unterschied: <em>damit</em> vs. <em>sodass</em>?",
     opts:["a) Kein Unterschied — beide drücken Folge aus.",
           "b) <em>damit</em> = Absicht (Final); <em>sodass</em> = Folge (Konsekutiv).",
           "c) <em>sodass</em> = Absicht; <em>damit</em> = Folge.",
           "d) <em>damit</em> kann nur bei gleichem Subjekt stehen."],
     ans:"b) <em>damit</em> = Absicht (Final); <em>sodass</em> = Folge (Konsekutiv).",
     exp:"<em>damit</em> = финальный коннектор (цель): «Er lernt, <em>damit</em> er besteht.» (чтобы). <em>sodass</em> = консекутивный (следствие): «Er lernte viel, <em>sodass</em> er bestand.» (так что). Разница: намерение vs. результат.",
     rule:"DAMIT = чтобы (цель/намерение). SODASS = так что (следствие/результат)."},
    {n:3,
     aufgabe:"«Das Ergebnis war ___ überzeugend, ___ alle zustimmten.»",
     opts:["a) so … dass","b) derart … sodass","c) zu … als dass","d) sowohl a) als auch b)"],
     ans:"d) sowohl a) als auch b)",
     exp:"<em>so … dass</em> und <em>derart … sodass</em> sind beide korrekte Konsekutivkonstruktionen. <em>so überzeugend, dass</em> = настолько убедительный, что. <em>derart überzeugend, sodass</em> = столь убедительный, что (высокий стиль).",
     rule:"SO + Adj. + DASS = настолько … что. DERART + Adj. + SODASS = то же, высокий стиль."},
    {n:4,
     aufgabe:"«Der Text ist ___ schwierig, ___ ihn Anfänger nicht verstehen können.»",
     opts:["a) so … dass","b) zu … als dass","c) derart … damit","d) so … sodass"],
     ans:"b) zu … als dass",
     exp:"<strong>zu + Adjektiv + als dass + Konjunktiv</strong> — особая консекутивная конструкция: «слишком … чтобы». «Der Text ist zu schwierig, als dass Anfänger ihn verstehen könnten.» Verb im Nebensatz = Konjunktiv II!",
     rule:"ZU … ALS DASS + Konjunktiv II: слишком … чтобы. Er ist zu müde, als dass er arbeiten könnte."},
    {n:5,
     aufgabe:"«___ du rechtzeitig ankommst, können wir noch zusammen essen.» — Konditional:",
     opts:["a) Obwohl","b) Sofern","c) Sodass","d) Damit"],
     ans:"b) Sofern",
     exp:"<strong>sofern</strong> = при условии, что; если (условие выполняется). «<em>Sofern</em> du rechtzeitig ankommst…» = если/при условии, что ты придёшь вовремя. Нейтральная/формальная альтернатива к <em>wenn</em>.",
     rule:"SOFERN = при условии что (= wenn, нейтрально). Также: falls (менее формально)."},
    {n:6,
     aufgabe:"«Er kommt zur Party, ___ er nicht krank wird.» — Negatives Konditional:",
     opts:["a) sofern","b) es sei denn, (dass)","c) vorausgesetzt dass","d) sobald"],
     ans:"b) es sei denn, (dass)",
     exp:"<strong>es sei denn, dass</strong> = если только не; разве что. «Er kommt, <em>es sei denn</em>, er wird krank.» = он придёт, если только не заболеет. Konj. I или II im Nebensatz möglich.",
     rule:"ES SEI DENN(, DASS) = если только не; разве что. Negatives Konditional!"},
    {n:7,
     aufgabe:"«___ dass alle Unterlagen vollständig sind, kann der Antrag bearbeitet werden.»",
     opts:["a) Sofern","b) Vorausgesetzt","c) Es sei denn","d) Obgleich"],
     ans:"b) Vorausgesetzt",
     exp:"<strong>vorausgesetzt, dass</strong> = при условии, что (формальный стиль). «<em>Vorausgesetzt</em>, dass alle Unterlagen vollständig sind…» = при условии, что все документы в порядке. Высокий/официальный регистр.",
     rule:"VORAUSGESETZT, DASS = при условии, что (официально). = sofern, wenn."},
    {n:8,
     aufgabe:"«Gesetzt den Fall, ___ er recht hätte — was dann?» — Welche Form?",
     opts:["a) das","b) dass","c) ob","d) wenn"],
     ans:"b) dass",
     exp:"<strong>gesetzt den Fall, dass</strong> = предположим, что; допустим, что. Устойчивое выражение с <em>dass</em>-Satz и Konjunktiv II: «Gesetzt den Fall, dass er recht hätte…»",
     rule:"GESETZT DEN FALL, DASS + Konjunktiv II = допустим, что (гипотетически)."},
    {n:9,
     aufgabe:"Welcher Satz enthält einen <em>finalen</em> (nicht konsekutiven) Nebensatz?",
     opts:["a) Er redete laut, sodass alle ihn hörten.",
           "b) Er redete laut, damit alle ihn hören konnten.",
           "c) Er redete so laut, dass alle aufwachten.",
           "d) Er redete laut, was alle störte."],
     ans:"b) Er redete laut, damit alle ihn hören konnten.",
     exp:"<strong>damit</strong> = финальный (цель): «чтобы все могли его слышать» — намерение говорящего. <em>sodass / so…dass</em> = консекутивный (следствие). <em>was</em> = относительный Nebensatz.",
     rule:"DAMIT = цель (Final). SODASS = следствие (Konsekutiv). Ключевой вопрос: намерение или результат?"},
    {n:10,
     aufgabe:"Ergänze: «Die Aufgabe war ___ komplex, ___ niemand sie allein lösen ___».» (C1-Konsekutiv)",
     opts:["a) so … dass … konnte","b) zu … als dass … könnte","c) derart … sodass … konnte","d) Sowohl a) als auch c) korrekt"],
     ans:"d) Sowohl a) als auch c) korrekt",
     exp:"<em>so komplex, dass niemand sie allein lösen konnte</em> (Indikativ = реальный факт) und <em>derart komplex, sodass niemand sie allein lösen konnte</em> (высокий стиль) — beide korrekt. <em>zu … als dass … könnte</em> wäre auch möglich mit Konjunktiv II.",
     rule:"KONSEKUTIV: so…dass (Ind.), derart…sodass (высокий), zu…als dass (Konj.II = слишком)."}
  ],
  vocab:["sodass — так что (следствие)","damit — чтобы (цель)","so … dass — настолько … что","zu … als dass — слишком … чтобы","sofern — при условии что","es sei denn(, dass) — если только не","vorausgesetzt, dass — при условии, что","gesetzt den Fall, dass — допустим, что","derart … sodass — столь … что (высокий стиль)"]
};
