// test-gr5.js — Grammatik: Konjunktiv II (Irrealis & hätte…sollen)
window.TELC_TEST = {
  id:"gr5", type:"Grammatik", kind:"gr",
  title:"Konjunktiv II: Irrealis · hätte sollen · wäre worden",
  desc:"10 Aufgaben · Hypothese & Kritik · C1",
  qs:[
    {n:1,
     aufgabe:"«Wenn ich mehr Zeit ___, ___ ich das Buch lesen.» — Konj. II Präsens:",
     opts:["a) hätte … würde","b) habe … werde","c) hatte … würde","d) hätte … werde"],
     ans:"a) hätte … würde",
     exp:"<strong>Konjunktiv II Präsens</strong> (Irrealis der Gegenwart): <em>hätte</em> (Konj.II von haben) + <em>würde</em> + Infinitiv. «Wenn ich mehr Zeit <em>hätte</em>, <em>würde</em> ich das Buch lesen.» = если бы у меня было больше времени, я бы прочитал.",
     rule:"IRREALIS GEGENWART: Wenn + Konj.II … würde + Inf. NICHT: wenn … hätte … würde lesen."},
    {n:2,
     aufgabe:"Irrealis der Vergangenheit: «Wenn er früher gekommen ___, ___ wir ihn getroffen.»",
     opts:["a) wäre … hätten","b) wäre … würden","c) hätte … wären","d) sei … hätten"],
     ans:"a) wäre … hätten",
     exp:"<strong>Konj.II Perfekt</strong> (Irrealis der Vergangenheit): wäre + Partizip II (für Bewegungsverben) / hätte + Partizip II (für haben-Verben). «Wenn er früher <em>gekommen wäre</em>, <em>hätten</em> wir ihn getroffen.»",
     rule:"IRREALIS VERGANGENHEIT: wäre/hätte + Part.II … hätte/wäre + Part.II."},
    {n:3,
     aufgabe:"Kritik an der Vergangenheit: «Du hättest früher kommen ___.»",
     opts:["a) sollen","b) solltest","c) solltest haben","d) gesollt"],
     ans:"a) sollen",
     exp:"<strong>hätte … sollen</strong> = упрёк за прошлое (ты должен был, но не сделал). «Du hättest früher kommen <em>sollen</em>.» = ты должен был прийти раньше. Тройной Infinitiv: hätte + Inf. + sollen (в порядке: Inf1 + Modalverb).",
     rule:"УПРЁК: hätte + Infinitiv + sollen/müssen/dürfen/können. Du hättest es machen sollen."},
    {n:4,
     aufgabe:"«Er ___ das Angebot annehmen ___ — aber er lehnte ab.»",
     opts:["a) sollte … sollen","b) hätte … sollen","c) würde … sollen","d) hätte … gesollt"],
     ans:"b) hätte … sollen",
     exp:"<strong>hätte … sollen</strong> = он должен был принять (но не принял). Упрёк или сожаление о прошлом. «Er <em>hätte</em> das Angebot annehmen <em>sollen</em>.»",
     rule:"HÄTTE + Inf. + SOLLEN = должен был (но не сделал). HÄTTE + Inf. + KÖNNEN = мог бы (но не сделал)."},
    {n:5,
     aufgabe:"«Das ___ vermieden werden ___ .» — Passiv Konjunktiv II Perfekt:",
     opts:["a) hätte … können","b) wäre … worden","c) hätte … werden können","d) hätte … worden können"],
     ans:"c) hätte … werden können",
     exp:"<strong>Passiv Konjunktiv II Perfekt mit Modalverb</strong>: hätte + Infinitiv + werden + können. «Das <em>hätte</em> vermieden werden <em>können</em>.» = это можно было бы предотвратить. Порядок в Nebensatz меняется.",
     rule:"PASSIV KONJ.II PERF. + MODAL: hätte + Inf. + werden + können/müssen/sollen."},
    {n:6,
     aufgabe:"«An seiner Stelle ___ ich anders entschieden.» — Konj.II:",
     opts:["a) würde … haben","b) hätte … entschieden","c) wäre … entschieden","d) hätte … entschieden haben"],
     ans:"b) hätte … entschieden",
     exp:"<strong>hätte entschieden</strong> = Konj.II Perfekt von <em>entscheiden</em> (haben-Verb). «An seiner Stelle <em>hätte</em> ich anders <em>entschieden</em>.» = на его месте я бы решил иначе. entscheiden → hat entschieden → hätte entschieden.",
     rule:"KONJ.II PERFEKT AKTIV: hätte/wäre + Part.II. entscheiden → hätte entschieden."},
    {n:7,
     aufgabe:"Wunsch in der Gegenwart: «Wenn er doch ___ hier!»",
     opts:["a) ist","b) wäre","c) sei","d) wird"],
     ans:"b) wäre",
     exp:"<strong>Wunsch mit Konjunktiv II</strong>: «Wenn er doch <em>wäre</em> hier!» = если бы он только был здесь! Für Wünsche der Gegenwart: wenn + Konj.II (+ doch/nur für Emphase).",
     rule:"WUNSCH GEGENWART: Wenn er doch + Konj.II! (wäre, hätte, käme…) + Partikel doch/nur."},
    {n:8,
     aufgabe:"Höfliche Bitte (Konj.II): Welche Form ist am höflichsten?",
     opts:["a) Können Sie mir helfen?","b) Könnten Sie mir helfen?","c) Sie helfen mir?","d) Würden Sie mir helfen?"],
     ans:"b) Könnten Sie mir helfen?",
     exp:"<strong>könnten</strong> = Konjunktiv II von <em>können</em> — стандарт вежливой просьбы на C1. <em>würden Sie</em> (d) — тоже вежливо, но <em>könnten</em> считается ещё более вежливым и деловым.",
     rule:"HÖFLICHKEIT: könnten/dürfte ich/würden Sie > können Sie (Indikativ = менее вежливо)."},
    {n:9,
     aufgabe:"«Es ___ besser gewesen, früher anzufangen.» — Konj.II Perfekt von <em>sein</em>:",
     opts:["a) war","b) ist","c) wäre","d) sei"],
     ans:"c) wäre",
     exp:"<strong>wäre</strong> = Konj.II von <em>sein</em>. «Es <em>wäre</em> besser gewesen, früher anzufangen.» = было бы лучше начать раньше. Конструкция: wäre + Adjektiv + gewesen + zu-Infinitiv.",
     rule:"WÄRE BESSER GEWESEN: Es wäre besser gewesen, + zu-Infinitiv. = было бы лучше."},
    {n:10,
     aufgabe:"«Das Projekt ___ effizienter durchgeführt werden ___ .» (Passiv + Möglichkeit + Vergangenheit)",
     opts:["a) konnte … werden","b) hätte … können werden","c) hätte … werden können","d) wäre … können worden"],
     ans:"c) hätte … werden können",
     exp:"<strong>hätte … werden können</strong> = Passiv + Modalverb (können) + Konj.II Perfekt. Reihenfolge im Hauptsatz: <em>hätte</em> [an Position 2] + … + werden + können [am Ende]. «Das Projekt <em>hätte</em> effizienter durchgeführt werden <em>können</em>.»",
     rule:"PASSIV + KONJ.II + MODAL PERFEKT: hätte + Part.II + werden + können (Hauptsatz)."}
  ],
  vocab:["Konjunktiv II — конъюнктив II (нереальное условие)","Irrealis — ирреалис (нереальное)","hätte … sollen — должен был (но не сделал)","hätte … können — мог бы (но не сделал)","wäre … worden — был бы (пассив прошедшего)","würde + Inf. — замена конъюнктива II","Wunschsatz — предложение-пожелание","könnten Sie — могли бы Вы (вежливо)"]
};
