// test-gr1.js — Grammatik: Modalsatz
window.TELC_TEST = {
  id:"gr1", type:"Grammatik", kind:"gr",
  title:"Modalsatz: indem · dadurch dass · ohne dass · anstatt dass",
  desc:"10 Aufgaben · Satzverbindungen · C1",
  qs:[
    {n:1,
     aufgabe:"Er verbessert sein Deutsch. Er liest jeden Tag Zeitung. → Verbinde mit <em>indem</em>:",
     opts:["a) Er verbessert sein Deutsch, indem er jeden Tag Zeitung liest.",
           "b) Er verbessert sein Deutsch, indem liest er jeden Tag Zeitung.",
           "c) Er verbessert sein Deutsch, dadurch er jeden Tag Zeitung liest.",
           "d) Er verbessert sein Deutsch, indem er jeden Tag Zeitung gelesen hat."],
     ans:"a) Er verbessert sein Deutsch, indem er jeden Tag Zeitung liest.",
     exp:"<strong>indem</strong> — придаточное способа действия. Порядок слов: подлежащее → глагол в конце. Время = время главного предложения (Präsens → Präsens).",
     rule:"INDEM: Er lernt, <em>indem</em> er Karteikarten macht. = тем, что / путём того, что."},
    {n:2,
     aufgabe:"Was ist der Unterschied zwischen <em>indem</em> und <em>dadurch, dass</em>?",
     opts:["a) Kein Unterschied — sie sind vollständig austauschbar.",
           "b) <em>dadurch, dass</em> leitet Hauptsätze ein, <em>indem</em> Nebensätze.",
           "c) <em>indem</em> steht im Nebensatz; <em>dadurch, dass</em> enthält ein Korrelat im Hauptsatz.",
           "d) <em>dadurch, dass</em> drückt Gegensatz aus, <em>indem</em> Bedingung."],
     ans:"c) <em>indem</em> steht im Nebensatz; <em>dadurch, dass</em> enthält ein Korrelat im Hauptsatz.",
     exp:"<em>dadurch, dass</em> = Korrelatkonstruktion: <em>dadurch</em> im Hauptsatz, <em>dass</em> leitet Nebensatz ein. Beispiel: Er hat Erfolg, <em>dadurch, dass</em> er hart arbeitet. Beide bedeuten dasselbe, aber Struktur unterscheidet sich.",
     rule:"DADURCH, DASS: Das Korrelat <em>dadurch</em> steht im Hauptsatz, <em>dass</em> leitet den Nebensatz ein."},
    {n:3,
     aufgabe:"Er hat die Prüfung bestanden. Er hat nicht gelernt. → Verbinde mit <em>ohne dass</em>:",
     opts:["a) Er hat die Prüfung bestanden, ohne dass er gelernt hat.",
           "b) Er hat die Prüfung bestanden, ohne er gelernt hat.",
           "c) Er hat die Prüfung bestanden, ohne zu lernen hat.",
           "d) Er hat die Prüfung bestanden, ohne dass er lernt."],
     ans:"a) Er hat die Prüfung bestanden, ohne dass er gelernt hat.",
     exp:"<strong>ohne dass</strong> — разные подлежащие → <em>ohne dass</em> + Nebensatz. Одинаковые подлежащие → <em>ohne zu</em> + Infinitiv. Здесь подлежащие одинаковые, но форма <em>ohne dass</em> тоже допустима.",
     rule:"OHNE DASS: разные подлежащие → <em>ohne dass</em>. Одинаковые → <em>ohne zu + Inf.</em>"},
    {n:4,
     aufgabe:"Welcher Satz ist korrekt? (Subjekt gleich in beiden Teilsätzen)",
     opts:["a) Er ging weg, ohne zu sagen etwas.",
           "b) Er ging weg, ohne etwas zu sagen.",
           "c) Er ging weg, ohne dass er etwas sagte.",
           "d) Sowohl b) als auch c) sind korrekt."],
     ans:"d) Sowohl b) als auch c) sind korrekt.",
     exp:"Bei gleichem Subjekt: <em>ohne zu + Infinitiv</em> (b) ist Standard. <em>ohne dass</em> (c) ist auch korrekt, aber stilistisch schwerer. Beide sind grammatisch.",
     rule:"OHNE ZU vs. OHNE DASS: Bei gleichem Subjekt bevorzugt man <em>ohne + zu-Inf.</em>"},
    {n:5,
     aufgabe:"Er schaut fern. Er macht keine Hausaufgaben. → Verbinde mit <em>anstatt … zu</em>:",
     opts:["a) Er schaut fern, anstatt zu machen Hausaufgaben.",
           "b) Er schaut fern, anstatt Hausaufgaben zu machen.",
           "c) Er schaut fern, anstatt dass Hausaufgaben er macht.",
           "d) Er schaut fern, statt Hausaufgaben gemacht zu haben."],
     ans:"b) Er schaut fern, anstatt Hausaufgaben zu machen.",
     exp:"<strong>anstatt … zu</strong>: bei gleichem Subjekt + Infinitiv mit <em>zu</em>. Das Nomen steht zwischen <em>anstatt</em> und <em>zu + Infinitiv</em>. Wortstellung: anstatt + [Rest] + zu + Infinitiv.",
     rule:"ANSTATT ZU: Er liest, <em>anstatt</em> fernzusehen. (ein Wort = keine Lücke) / anstatt [Nomen] zu [Verb]."},
    {n:6,
     aufgabe:"Ergänze das Korrelat: «Er hat die Stelle bekommen, ___ dass er gut vorbereitet war.»",
     opts:["a) indem","b) womit","c) dadurch","d) wodurch"],
     ans:"c) dadurch",
     exp:"<strong>dadurch, dass</strong> — das Korrelat im Hauptsatz ist immer <em>dadurch</em>. «Er hat die Stelle bekommen, <em>dadurch</em>, dass er gut vorbereitet war.»",
     rule:"KORRELAT: dadurch → dadurch, dass | womit → womit (Relativsatz) | wodurch → Frage nach dem Mittel."},
    {n:7,
     aufgabe:"«Die Firma steigerte ihren Umsatz, ___ sie in neue Märkte expandierte.» — Welcher Konnektor passt?",
     opts:["a) ohne dass","b) anstatt dass","c) indem","d) sodass"],
     ans:"c) indem",
     exp:"<strong>indem</strong> drückt aus, WIE / auf welche Weise die Firma den Umsatz steigerte. <em>sodass</em> wäre Konsekutivsatz (Folge), <em>ohne dass</em> ist negativ.",
     rule:"INDEM = способ действия (wie?). SODASS = следствие (mit welcher Folge?)."},
    {n:8,
     aufgabe:"«Er antwortete auf die E-Mail, ___ er den Anhang vergaß.» Welcher Konnektor?",
     opts:["a) indem","b) ohne dass","c) wobei","d) sodass"],
     ans:"c) wobei",
     exp:"<strong>wobei</strong> — сопутствующее обстоятельство («при этом»). Nicht <em>indem</em> (Methode), nicht <em>ohne dass</em> (negativ), nicht <em>sodass</em> (Folge).",
     rule:"WOBEI = при этом / причём. Er half mir, <em>wobei</em> er selbst kaum Zeit hatte."},
    {n:9,
     aufgabe:"«Sie löste das Problem, ___ alle überrascht waren.» — Konsekutiv oder Modal?",
     opts:["a) indem — Modal","b) wodurch — Konsekutiv","c) ohne dass — Negation","d) anstatt dass — Adversativ"],
     ans:"b) wodurch — Konsekutiv",
     exp:"<strong>wodurch</strong> = «вследствие чего» — вводит следствие. «Sie löste das Problem, <em>wodurch</em> alle überrascht waren.» = durch das Lösen des Problems waren alle überrascht.",
     rule:"WODURCH = вследствие чего (Konsekutiv). WOMIT = чем (Mittel/Instrument)."},
    {n:10,
     aufgabe:"Welcher Satz ist C1-stilistisch korrekt und bevorzugt?",
     opts:["a) Er hat geholfen, ohne dass er etwas gesagt hat.",
           "b) Er hat geholfen, ohne etwas zu sagen.",
           "c) Er hat geholfen und hat dabei nichts gesagt.",
           "d) Er hat geholfen, indem er nichts sagte."],
     ans:"b) Er hat geholfen, ohne etwas zu sagen.",
     exp:"Bei gleichem Subjekt ist <em>ohne + zu-Infinitiv</em> (b) der präzisere und stilistisch bevorzugte Ausdruck auf C1. Option c) ist umgangssprachlicher, d) ist inhaltlich falsch (<em>indem</em> = Methode, nicht Begleitung).",
     rule:"C1-STIL: ohne zu + Inf. > ohne dass (bei gleichem Subjekt). Präzision hat Vorrang."}
  ],
  vocab:["indem — тем, что; путём того, что","dadurch, dass — вследствие того, что","ohne dass — без того, чтобы","anstatt zu — вместо того, чтобы","wobei — при этом, причём","wodurch — вследствие чего","womit — чем, с помощью чего","das Korrelat — коррелят (местоимение-предвосхищение)"]
};
