// test-gr2.js — Grammatik: Konzessivsatz
window.TELC_TEST = {
  id:"gr2", type:"Grammatik", kind:"gr",
  title:"Konzessivsatz: obwohl · wenngleich · auch wenn · gleichwohl",
  desc:"10 Aufgaben · Konzession · C1",
  qs:[
    {n:1,
     aufgabe:"«___ er müde war, arbeitete er bis Mitternacht.» Welcher Konnektor passt?",
     opts:["a) Obwohl","b) Weil","c) Indem","d) Sodass"],
     ans:"a) Obwohl",
     exp:"<strong>Obwohl</strong> — вводит концессивное придаточное (уступительное). «Хотя он был устал, он работал до полуночи.» Порядок слов: Verb an letzter Stelle im Nebensatz.",
     rule:"OBWOHL: концессия (хотя). Nebensatz: Subj. + ... + Verb am Ende."},
    {n:2,
     aufgabe:"Welcher Konnektor ist ein gehobenes Synonym zu <em>obwohl</em>?",
     opts:["a) sodass","b) wenngleich","c) sofern","d) indem"],
     ans:"b) wenngleich",
     exp:"<strong>wenngleich</strong> (= obgleich, obschon) — книжный/высокий стиль, синоним obwohl. «Wenngleich es regnete, gingen sie spazieren.» Употребляется в письменных/формальных текстах C1.",
     rule:"WENNGLEICH = obwohl (высокий стиль). Также: obgleich, obschon, wiewohl."},
    {n:3,
     aufgabe:"«Er kam zur Arbeit, ___ er krank war.» — Welche ZWEI Konnektoren passen?",
     opts:["a) obwohl / trotzdem","b) obwohl / obgleich","c) weil / da","d) sodass / weshalb"],
     ans:"b) obwohl / obgleich",
     exp:"<strong>obwohl</strong> und <strong>obgleich</strong> leiten beide Nebensätze ein (Verb am Ende). <em>trotzdem</em> leitet Hauptsätze ein (Pos.1 → Verb an Pos.2): «Er war krank, trotzdem kam er zur Arbeit.»",
     rule:"NEBENSATZ: obwohl, obgleich, wenngleich → Verb am Ende. HAUPTSATZ: trotzdem, dennoch, gleichwohl → Verb an Pos.2."},
    {n:4,
     aufgabe:"«Das Projekt war teuer. ___ wurde es genehmigt.» — Konzessiv im Hauptsatz:",
     opts:["a) Obwohl","b) Trotzdem","c) Wenngleich","d) Obgleich"],
     ans:"b) Trotzdem",
     exp:"<strong>trotzdem</strong> — коннектор главного предложения (Hauptsatzkonnektor). Стоит на позиции 1, глагол на позиции 2: «Das Projekt war teuer. <em>Trotzdem</em> wurde es genehmigt.»",
     rule:"TROTZDEM = тем не менее (Hauptsatz, Pos.1). DENNOCH, GLEICHWOHL = то же, книжный стиль."},
    {n:5,
     aufgabe:"«___ auch viele dagegen protestierten, wurde das Gesetz verabschiedet.»",
     opts:["a) Auch wenn","b) Sodass","c) Indem","d) Damit"],
     ans:"a) Auch wenn",
     exp:"<strong>auch wenn</strong> — концессивный Nebensatz с гипотетическим/реальным оттенком: «даже если / хотя и». Употребляется, когда говорящий допускает факт и всё равно утверждает главное.",
     rule:"AUCH WENN = даже если / хотя. Вводит Nebensatz (Verb am Ende). Схожее: selbst wenn."},
    {n:6,
     aufgabe:"Unterschied: <em>auch wenn</em> vs. <em>selbst wenn</em>?",
     opts:["a) Kein Unterschied.",
           "b) <em>selbst wenn</em> betont die Extremität der Bedingung stärker.",
           "c) <em>auch wenn</em> ist nur für Vergangenheit.",
           "d) <em>selbst wenn</em> kann nur im Konjunktiv II stehen."],
     ans:"b) <em>selbst wenn</em> betont die Extremität der Bedingung stärker.",
     exp:"<em>selbst wenn</em> = «даже если» (с акцентом на крайнем случае). «Selbst wenn es regnet, gehe ich spazieren.» = даже в этом крайнем случае. <em>auch wenn</em> — мягче, нейтральнее.",
     rule:"SELBST WENN = даже если (акцент на крайности). AUCH WENN = хотя / даже если (нейтрально)."},
    {n:7,
     aufgabe:"«Das Angebot war attraktiv. ___ lehnten wir es ab.» — Formal/schriftlich:",
     opts:["a) Trotzdem","b) Gleichwohl","c) Dennoch","d) Sowohl b) als auch c)"],
     ans:"d) Sowohl b) als auch c)",
     exp:"<strong>gleichwohl</strong> und <strong>dennoch</strong> sind beide formal/schriftsprachlich und bedeuten dasselbe wie <em>trotzdem</em>. <em>trotzdem</em> ist korrekter, aber neutraler. Für C1-Schreiben bevorzugt man <em>gleichwohl</em> oder <em>dennoch</em>.",
     rule:"DENNOCH / GLEICHWOHL = тем не менее (формальный стиль). = trotzdem."},
    {n:8,
     aufgabe:"«___ seiner Erfahrung konnte er das Problem nicht lösen.» — Prepositionaler Konzessivausdruck:",
     opts:["a) Trotz","b) Wegen","c) Dank","d) Aufgrund"],
     ans:"a) Trotz",
     exp:"<strong>trotz + Genitiv</strong> = несмотря на. «Trotz seiner Erfahrung…» = несмотря на его опыт. Ersetzt <em>obwohl er erfahren war</em>. C1: Präposition statt Nebensatz = kompakter Stil.",
     rule:"TROTZ + Genitiv = несмотря на. Ср.: aufgrund (вследствие), dank (благодаря), wegen (из-за)."},
    {n:9,
     aufgabe:"«Ungeachtet ___ Widerstands setzte er seinen Plan um.» — Welche Form?",
     opts:["a) des","b) dem","c) den","d) der"],
     ans:"a) des",
     exp:"<strong>ungeachtet + Genitiv</strong> = невзирая на. «Ungeachtet <em>des</em> Widerstands» — мужской род, Genitiv: des Widerstandes. Stilistisch высокий, синоним <em>trotz</em>.",
     rule:"UNGEACHTET + Genitiv = невзирая на (высокий стиль). Синоним: trotz + Genitiv."},
    {n:10,
     aufgabe:"Welcher Satz ist grammatisch FALSCH?",
     opts:["a) Obwohl er krank war, kam er zur Arbeit.",
           "b) Trotzdem er krank war, kam er zur Arbeit.",
           "c) Er war krank, trotzdem kam er zur Arbeit.",
           "d) Er war krank, dennoch kam er zur Arbeit."],
     ans:"b) Trotzdem er krank war, kam er zur Arbeit.",
     exp:"<strong>trotzdem</strong> ist ein Hauptsatzkonnektor — er kann keinen Nebensatz einleiten. Korrekt: <em>Obwohl er krank war, …</em> (Nebensatz). «Trotzdem er…» ist ein typischer Fehler auch bei fortgeschrittenen Lernenden.",
     rule:"FEHLER: *trotzdem er… → KORREKT: obwohl er… (Nebensatz) oder trotzdem + Hauptsatz."}
  ],
  vocab:["obwohl — хотя","wenngleich — хотя (высокий стиль)","obgleich — хотя (книжный)","trotzdem — тем не менее","dennoch — тем не менее (формально)","gleichwohl — тем не менее (книжный)","auch wenn — даже если / хотя","selbst wenn — даже если (акцент на крайности)","trotz + Gen. — несмотря на","ungeachtet + Gen. — невзирая на"]
};
