// test-gr7.js — Grammatik: Partizipialkonstruktionen
window.TELC_TEST = {
  id:"gr7", type:"Grammatik", kind:"gr",
  title:"Partizipialkonstruktionen: Partizip I & II als Attribut",
  desc:"10 Aufgaben · Erweiterte Partizipialgruppen · C1",
  qs:[
    {n:1,
     aufgabe:"«das weinende Kind» — Was drückt Partizip I aus?",
     opts:["a) Abgeschlossene Handlung (das Kind hat geweint).",
           "b) Gleichzeitige, aktive Handlung (das Kind weint gerade).",
           "c) Passive Handlung (das Kind wird zum Weinen gebracht).",
           "d) Zukünftige Handlung."],
     ans:"b) Gleichzeitige, aktive Handlung (das Kind weint gerade).",
     exp:"<strong>Partizip I</strong> (Infinitiv + d) = одновременное, активное действие. «das weinende Kind» = ребёнок, который плачет (сейчас). Не завершённое и не пассивное.",
     rule:"PARTIZIP I = Inf. + d + Adjektivendung. Aktiv + gleichzeitig. lachen → lachend → das lachende Kind."},
    {n:2,
     aufgabe:"«das renovierte Gebäude» — Partizip II als Attribut bedeutet:",
     opts:["a) Das Gebäude wird gerade renoviert.",
           "b) Das Gebäude, das renoviert wurde (abgeschlossen, passiv).",
           "c) Das Gebäude, das renovieren wird.",
           "d) Das Gebäude, das renoviert hat."],
     ans:"b) Das Gebäude, das renoviert wurde (abgeschlossen, passiv).",
     exp:"<strong>Partizip II</strong> als Attribut = abgeschlossen + passiv (bei transitiven Verben). «das renovierte Gebäude» = здание, которое было отремонтировано. Ersetzt Relativsatz: «das Gebäude, das renoviert wurde.»",
     rule:"PARTIZIP II Attribut (transitiv) = Passiv + abgeschlossen. renovieren → renoviert → das renovierte Gebäude."},
    {n:3,
     aufgabe:"Erweiterte Partizipialgruppe: «Die ___ Lösung» → Vollform: «die Lösung, die von allen akzeptiert wurde»",
     opts:["a) alle akzeptierende","b) von allen akzeptierte","c) von allen akzeptierende","d) akzeptierte von allen"],
     ans:"b) von allen akzeptierte",
     exp:"<strong>Erweiterte Partizipialgruppe</strong>: Partizip II + Erweiterungen stehen VOR dem Nomen. «die von allen akzeptierte Lösung» = Lösung, die von allen akzeptiert wurde. Adj.-Endung nach Artikel: -e (fem. Nom.).",
     rule:"ERWEITERTES PARTIZIPIALATTRIBUT: der/die/das + [Erweiterungen] + Part.II/I + Adj.endung + Nomen."},
    {n:4,
     aufgabe:"Wandle um in Partizipialattribut: «der Bericht, der gestern veröffentlicht wurde»",
     opts:["a) der gestern veröffentlichende Bericht","b) der gestern veröffentlicht Bericht","c) der gestern veröffentlichte Bericht","d) der gestern veröffentlichende worden Bericht"],
     ans:"c) der gestern veröffentlichte Bericht",
     exp:"<strong>der gestern veröffentlichte Bericht</strong>: Partizip II (<em>veröffentlicht</em>) + starke Adj.endung (der… → -e). Das Adverb <em>gestern</em> steht vor dem Partizip. Typische C1-Verdichtung von Relativsätzen.",
     rule:"RELATIVSATZ → PARTIZIPIALATTRIBUT: der Bericht, der … wurde → der … -te Bericht."},
    {n:5,
     aufgabe:"«Die ___ Zahl an Beschwerden alarmierte die Behörden.» (wachsen — Partizip I)",
     opts:["a) gewachsene","b) wachsende","c) wachsend","d) gewachsend"],
     ans:"b) wachsende",
     exp:"<strong>wachsende</strong> = Partizip I von <em>wachsen</em> + Adj.endung -e (fem.). «Die <em>wachsende</em> Zahl» = растущее число. Aktiv + gleichzeitig. Nicht <em>gewachsene</em> (Part.II = abgeschlossenes Wachstum).",
     rule:"WACHSEN → wachsend → die wachsende Zahl (aktiv, gleichzeitig). Gegenteil: die gewachsene Zahl (Ergebnis)."},
    {n:6,
     aufgabe:"Sein-Verb Partizip II als Attribut: «der angekommene Zug» bedeutet:",
     opts:["a) Der Zug, der gerade ankommt.",
           "b) Der Zug, der angekommen ist (abgeschlossen, aktiv).",
           "c) Der Zug, der ankommt werden wird.",
           "d) Der Zug, der angekommen wurde."],
     ans:"b) Der Zug, der angekommen ist (abgeschlossen, aktiv).",
     exp:"<strong>Sein-Verben</strong> (ankommen, kommen, gehen…): Partizip II = abgeschlossen + AKTIV (nicht passiv!). «der angekommene Zug» = поезд, который приехал. Ср.: <em>das gebaute Haus</em> = пассив (дом, который построили).",
     rule:"SEIN-VERB + Part.II Attribut = aktiv + abgeschlossen. ankommen → der angekommene Zug."},
    {n:7,
     aufgabe:"Welcher Satz ist KORREKT umgewandelt? Original: «die Studentin, die fleißig lernt»",
     opts:["a) die fleißig lernende Studentin","b) die fleißig gelernte Studentin","c) die fleißige lernende Studentin","d) die Studentin, fleißig lernend"],
     ans:"a) die fleißig lernende Studentin",
     exp:"<strong>die fleißig lernende Studentin</strong>: Partizip I (<em>lernen</em> → <em>lernend</em>) + Adj.endung -e + Adverb <em>fleißig</em> davor. Aktiv + gleichzeitig. <em>gelernte</em> (b) wäre passiv/abgeschlossen — falsch hier.",
     rule:"Relativsatz mit Aktivem Verb (Präsens) → Partizip I: lernen → lernend → lernende Studentin."},
    {n:8,
     aufgabe:"Auflösen: «die seit Jahren diskutierte Frage» → Relativsatz:",
     opts:["a) die Frage, die seit Jahren diskutiert",
           "b) die Frage, die seit Jahren diskutiert wird",
           "c) die Frage, die seit Jahren diskutieren wird",
           "d) die Frage, die seit Jahren diskutiert hat"],
     ans:"b) die Frage, die seit Jahren diskutiert wird",
     exp:"«die seit Jahren diskutierte Frage» = Partizip II von <em>diskutieren</em> (transitiv) = Passiv. Auflösung: «die Frage, die seit Jahren diskutiert wird.» Das Adverbial <em>seit Jahren</em> gehört dazu.",
     rule:"AUFLÖSUNG: [Erweiterung + Part.II] + Nomen → Nomen, das + [Erweiterung] + wird/wurde."},
    {n:9,
     aufgabe:"C1-Stil: Welcher Ausdruck ist am kompaktesten und schriftsprachlich korrekt?",
     opts:["a) der Mann, der sehr schnell läuft",
           "b) der sehr schnell laufende Mann",
           "c) der Mann der sehr schnell laufende",
           "d) der Mann, sehr schnell laufend"],
     ans:"b) der sehr schnell laufende Mann",
     exp:"<strong>der sehr schnell laufende Mann</strong>: Partizipialattribut ist im Schriftdeutschen die kompakte, bevorzugte Form. Keine Kommata, keine Periphrase. Auf C1-Niveau wird diese Form als Zeichen sprachlicher Gewandtheit bewertet.",
     rule:"SCHRIFTDEUTSCH C1: Partizipialattribut > Relativsatz. Kompaktheit = stilistische Kompetenz."},
    {n:10,
     aufgabe:"Partizip I mit passiver Bedeutung (Gerundiv): «das zu lösende Problem» bedeutet:",
     opts:["a) das Problem, das gelöst wurde",
           "b) das Problem, das zu lösen ist / gelöst werden muss",
           "c) das Problem, das löst",
           "d) das Problem, das sich löst"],
     ans:"b) das Problem, das zu lösen ist / gelöst werden muss",
     exp:"<strong>zu + Partizip I (Gerundiv)</strong> = Notwendigkeit/Möglichkeit (passiv). «das zu lösende Problem» = проблема, которую нужно решить / которую можно решить. C1-Konstruktion! Sehr häufig in wissenschaftlichen/offiziellen Texten.",
     rule:"GERUNDIV: zu + Inf. + d + Adj.endung = muss/kann + Passiv. das zu lösende Problem = мuss gelöst werden."}
  ],
  vocab:["Partizip I — причастие настоящего времени (Inf.+d)","Partizip II — причастие прошедшего времени","Partizipialattribut — причастный оборот в роли определения","erweiterte Partizipialgruppe — развёрнутая причастная группа","Gerundiv — герундив (zu + Part.I)","Relativsatz — придаточное определительное","transitiv — переходный глагол","Sein-Verb — глагол с вспомогательным sein"]
};
