// test-gr4.js — Grammatik: Konjunktiv I (Indirekte Rede)
window.TELC_TEST = {
  id:"gr4", type:"Grammatik", kind:"gr",
  title:"Konjunktiv I: Indirekte Rede",
  desc:"10 Aufgaben · Indirekte Rede · C1",
  qs:[
    {n:1,
     aufgabe:"Direkte Rede: «Ich bin sehr müde.» → Indirekte Rede (3. Person Sg.):",
     opts:["a) Er sagt, dass er sehr müde ist.",
           "b) Er sagt, er sei sehr müde.",
           "c) Er sagt, er wäre sehr müde.",
           "d) Er sagt, dass er sehr müde wäre."],
     ans:"b) Er sagt, er sei sehr müde.",
     exp:"<strong>Konjunktiv I</strong> — стандартная форма косвенной речи в письменном/формальном немецком. «sei» = Konj.I von <em>sein</em>. Option a) (Indikativ) и d) (Konj.II) допустимы разговорно, но не являются нормой письменного C1.",
     rule:"KONJUNKTIV I: ich bin → er sei. Используется в репортажах, официальных текстах, прессе."},
    {n:2,
     aufgabe:"Bilden Sie Konjunktiv I: <em>haben</em> (3. Person Singular)",
     opts:["a) hätte","b) hat","c) habe","d) haben"],
     ans:"c) habe",
     exp:"<strong>habe</strong> = Konjunktiv I von <em>haben</em> (3. Sg.). Схема: Infinitivstamm + e: hab-e. Nicht zu verwechseln mit <em>hätte</em> (Konjunktiv II).",
     rule:"KON.I от haben: ich habe, du habest, er/sie habe, wir haben, ihr habet, sie haben. KON.II: hätte."},
    {n:3,
     aufgabe:"«Die Ministerin erklärte, das Projekt ___ erfolgreich abgeschlossen worden.» (Passiv, Konjunktiv I Perfekt)",
     opts:["a) wurde","b) sei … worden","c) wäre … worden","d) ist … worden"],
     ans:"b) sei … worden",
     exp:"<strong>Konjunktiv I Perfekt Passiv</strong>: sei + Partizip II + worden. «Das Projekt <em>sei</em> erfolgreich abgeschlossen <em>worden</em>.» <em>wäre</em> (Konj.II) wäre zu verwenden, wenn Konj.I und Indikativ identisch wären.",
     rule:"KONJ.I PERFEKT PASSIV: sei + Part.II + worden. KONJ.I PERFEKT AKTIV: habe + Part.II."},
    {n:4,
     aufgabe:"Wann verwendet man Konjunktiv II statt Konjunktiv I in der indirekten Rede?",
     opts:["a) Immer bei Vergangenheit.",
           "b) Wenn die Konjunktiv-I-Form mit dem Indikativ identisch ist.",
           "c) Nur bei Modalverben.",
           "d) Wenn das Subjekt in der 1. Person steht."],
     ans:"b) Wenn die Konjunktiv-I-Form mit dem Indikativ identisch ist.",
     exp:"Wenn Konj.I = Indikativ (z.B. Plural: <em>sie haben</em> → Konj.I auch <em>haben</em> = nicht unterscheidbar), verwendet man Konj.II: <em>sie hätten</em>. So bleibt klar, dass es sich um indirekte Rede handelt.",
     rule:"REGEL: Konj.I → wenn ident. mit Indikativ → Konj.II verwenden. Z.B.: sie gehen → sie gingen (K.II)."},
    {n:5,
     aufgabe:"«Der Zeuge behauptete, er ___ die Person nicht gekannt.» — Konjunktiv I Perfekt:",
     opts:["a) hatte … nicht gekannt","b) habe … nicht gekannt","c) hätte … nicht gekannt","d) hat … nicht gekannt"],
     ans:"b) habe … nicht gekannt",
     exp:"<strong>habe … nicht gekannt</strong> = Konj.I Perfekt Aktiv: habe + Partizip II. <em>hätte</em> (c) = Konj.II — auch möglich, wenn Konj.I identisch mit Indikativ wäre, aber hier ist <em>habe</em> eindeutig.",
     rule:"KONJ.I PERFEKT: habe/sei + Part.II. KONJ.II PERFEKT: hätte/wäre + Part.II."},
    {n:6,
     aufgabe:"Bilden Sie Konjunktiv I von <em>können</em> (3. Person Sg.):",
     opts:["a) kann","b) könnte","c) könne","d) gekonnt"],
     ans:"c) könne",
     exp:"<strong>könne</strong> = Konjunktiv I von <em>können</em> (3. Sg.). Bei Modalverben: Umlaut fällt weg. könn-en → könn-e. Nicht <em>könnte</em> (das ist Konj.II).",
     rule:"MODALVERBEN Konj.I: dürfe, könne, möge, müsse, solle, wolle (без умляута Konj.II!)."},
    {n:7,
     aufgabe:"«Laut Bericht ___ die Kosten deutlich gestiegen.» — Welche Form?",
     opts:["a) sind","b) seien","c) wären","d) waren"],
     ans:"b) seien",
     exp:"<strong>seien</strong> = Konj.I von <em>sein</em>, Plural (3. Pl.). In Berichten/Pressetexten: «Laut Bericht <em>seien</em> die Kosten gestiegen.» <em>wären</em> = Konj.II — zu verwenden, wenn <em>seien</em> nicht eindeutig wäre.",
     rule:"PRESSE/BERICHTE: laut + Konj.I. seien = Konj.I Plural von sein. wären = Konj.II."},
    {n:8,
     aufgabe:"«Der Sprecher betonte, die Entscheidung ___ noch nicht gefallen.» (3. Sg., Verb: fallen — sein-Verb)",
     opts:["a) hat","b) habe","c) sei","d) wäre"],
     ans:"c) sei",
     exp:"<strong>sei</strong> = Konj.I Perfekt von <em>fallen</em> (Hilfsverb: sein). «Die Entscheidung <em>sei</em> noch nicht gefallen.» = sei + Partizip II ohne Partizip hier — falsch, korrekter Satz wäre: <em>sei … noch nicht gefallen</em>.",
     rule:"SEIN-VERBEN Perfekt Konj.I: sei + Part.II (fallen → sei gefallen, kommen → sei gekommen)."},
    {n:9,
     aufgabe:"Indirekte Rede: «Wir werden das Problem lösen.» → Singular nicht möglich — welcher Konj. II?",
     opts:["a) würden das Problem lösen","b) werden das Problem lösen","c) lösten das Problem","d) hätten das Problem gelöst"],
     ans:"a) würden das Problem lösen",
     exp:"Konj.I von <em>werden</em> (Plural) = <em>werden</em> — identisch mit Indikativ! Daher: Konj.II = <em>würden</em>. «Sie sagten, sie <em>würden</em> das Problem lösen.» Würde-Konstruktion als Ersatz für Konj.I.",
     rule:"WÜRDE-KONSTRUKTION: wenn Konj.I = Indikativ (bes. Plural), nimmt man würde + Infinitiv."},
    {n:10,
     aufgabe:"Welcher Satz ist für einen Pressebericht (C1) KORREKT und BEVORZUGT?",
     opts:["a) Der Minister sagte, dass er das Gesetz unterzeichnen wird.",
           "b) Der Minister sagte, er würde das Gesetz unterzeichnen.",
           "c) Der Minister sagte, er werde das Gesetz unterzeichnen.",
           "d) Der Minister sagte, er wird das Gesetz unterzeichnen."],
     ans:"c) Der Minister sagte, er werde das Gesetz unterzeichnen.",
     exp:"<strong>werde</strong> = Konjunktiv I von <em>werden</em> (Singular, 3. Pers.) — eindeutig, da «werde» ≠ «wird» (Indikativ). Für Pressetexte: Konj.I ist Standard. Option b) (<em>würde</em>) ist Ausweich-Konj.II, wird akzeptiert, aber Konj.I ist präziser.",
     rule:"PRESSE-STANDARD: werde (Konj.I Sg.) bevorzugt vor würde (Konj.II). Nur bei Ambiguität → Konj.II."}
  ],
  vocab:["Konjunktiv I — конъюнктив I (косвенная речь)","die indirekte Rede — косвенная речь","sei — конъюнктив I от sein (3.Sg.)","habe — конъюнктив I от haben (3.Sg.)","könne — конъюнктив I от können","werde — конъюнктив I от werden (Sg.)","seien — конъюнктив I от sein (Pl.)","laut + Konj.I — согласно (репортаж)","würde-Konstruktion — конструкция-замена конъюнктива I"]
};
