// test-gr8.js — Grammatik: Funktionsverbgefüge
window.TELC_TEST = {
  id:"gr8", type:"Grammatik", kind:"gr",
  title:"Funktionsverbgefüge: zur Verfügung · in Frage · Bezug nehmen",
  desc:"10 Aufgaben · Nomen-Verb-Verbindungen · C1",
  qs:[
    {n:1,
     aufgabe:"«Diese Ressourcen stehen uns ___ Verfügung.» — Welche Präposition?",
     opts:["a) zu","b) zur","c) in","d) für"],
     ans:"b) zur",
     exp:"<strong>zur Verfügung stehen</strong> = быть в распоряжении. <em>zur</em> = zu + der (Dativ, fem.). «Diese Ressourcen stehen uns <em>zur</em> Verfügung.» Synonyme: verfügbar sein, vorhanden sein.",
     rule:"ZUR VERFÜGUNG STEHEN = быть в распоряжении. ZUR VERFÜGUNG STELLEN = предоставлять."},
    {n:2,
     aufgabe:"«Sein Vorschlag kommt ___ Frage.» bedeutet:",
     opts:["a) Sein Vorschlag ist möglich / kann berücksichtigt werden.",
           "b) Sein Vorschlag ist unmöglich.",
           "c) Sein Vorschlag wird befragt.",
           "d) Sein Vorschlag ist fraglich."],
     ans:"a) Sein Vorschlag ist möglich / kann berücksichtigt werden.",
     exp:"<strong>in Frage kommen</strong> = быть возможным, рассматриваться как вариант. «Sein Vorschlag kommt <em>in Frage</em>.» ≠ <em>in Frage stellen</em> (поставить под сомнение). Nicht zu verwechseln!",
     rule:"IN FRAGE KOMMEN = рассматриваться, подходить. IN FRAGE STELLEN = ставить под сомнение."},
    {n:3,
     aufgabe:"«Er stellte die Entscheidung ___ Frage.» — Bedeutung:",
     opts:["a) Er fragte nach der Entscheidung.",
           "b) Er bezweifelte / kritisierte die Entscheidung.",
           "c) Die Entscheidung wurde beantwortet.",
           "d) Er stellte eine Frage über die Entscheidung."],
     ans:"b) Er bezweifelte / kritisierte die Entscheidung.",
     exp:"<strong>in Frage stellen</strong> = ставить под сомнение, подвергать сомнению. «Er stellte die Entscheidung <em>in Frage</em>.» = он поставил решение под сомнение. Sehr häufig im akademischen/offiziellen Schreiben.",
     rule:"IN FRAGE STELLEN = ставить под сомнение (kritisieren). ≠ in Frage kommen (возможный вариант)."},
    {n:4,
     aufgabe:"«Sie nahm ___ den Bericht Bezug.» — Welche Präposition?",
     opts:["a) auf","b) in","c) an","d) zu"],
     ans:"a) auf",
     exp:"<strong>Bezug nehmen auf + Akk.</strong> = ссылаться на что-либо. «Sie nahm <em>auf</em> den Bericht Bezug.» = она сослалась на доклад. Formeller Ausdruck für <em>sich beziehen auf</em>.",
     rule:"BEZUG NEHMEN AUF + Akk. = ссылаться на (= sich beziehen auf). Formell, C1."},
    {n:5,
     aufgabe:"«Das Unternehmen zog seinen Antrag ___ Betracht.» → in Betracht ziehen bedeutet:",
     opts:["a) einen Antrag einreichen","b) einen Antrag zurückziehen","c) etwas berücksichtigen / erwägen","d) etwas ablehnen"],
     ans:"c) etwas berücksichtigen / erwägen",
     exp:"<strong>in Betracht ziehen</strong> = рассматривать, принимать во внимание. «Das Unternehmen zog seinen Antrag in Betracht.» — ABER: Logisch wäre hier: zog eine Alternative in Betracht. In Betracht = в расчёт, во внимание.",
     rule:"IN BETRACHT ZIEHEN = принимать во внимание / рассматривать вариант. Formell."},
    {n:6,
     aufgabe:"«Die Behörde setzte das Gesetz ___ Kraft.» — Bedeutung:",
     opts:["a) Das Gesetz wurde abgeschafft.",
           "b) Das Gesetz wurde für ungültig erklärt.",
           "c) Das Gesetz trat in Kraft / wurde wirksam.",
           "d) Das Gesetz wurde diskutiert."],
     ans:"c) Das Gesetz trat in Kraft / wurde wirksam.",
     exp:"<strong>in Kraft setzen</strong> = вводить в действие (закон). «Die Behörde setzte das Gesetz <em>in Kraft</em>.» ≠ außer Kraft setzen (отменять). Gegenpaar wichtig auf C1!",
     rule:"IN KRAFT SETZEN = вводить в действие. AUßER KRAFT SETZEN = отменять, выводить из силы."},
    {n:7,
     aufgabe:"«Er brachte seine Ideen ___ Ausdruck.» — zum Ausdruck bringen bedeutet:",
     opts:["a) Ideen aufschreiben","b) Ideen ausdrücken / äußern","c) Ideen kritisieren","d) Ideen verwerfen"],
     ans:"b) Ideen ausdrücken / äußern",
     exp:"<strong>zum Ausdruck bringen</strong> = выражать, высказывать. «Er brachte seine Ideen <em>zum Ausdruck</em>.» = er äußerte / formulierte seine Ideen. Synonym: zum Vorschein bringen (проявить).",
     rule:"ZUM AUSDRUCK BRINGEN = выражать (= ausdrücken, формально). ZUM AUSDRUCK KOMMEN = проявляться."},
    {n:8,
     aufgabe:"Welches Funktionsverbgefüge bedeutet «anfangen»?",
     opts:["a) in Angriff nehmen","b) in Kauf nehmen","c) in Frage stellen","d) in Betracht kommen"],
     ans:"a) in Angriff nehmen",
     exp:"<strong>in Angriff nehmen</strong> = приступать к чему-либо, браться за дело. «Wir nehmen das Projekt in Angriff.» = мы приступаем к проекту. <em>in Kauf nehmen</em> = мириться с чем-то (нежелательным).",
     rule:"IN ANGRIFF NEHMEN = приступать к. IN KAUF NEHMEN = мириться с (нежелательным)."},
    {n:9,
     aufgabe:"«Sie müssen die Nachteile ___ Kauf nehmen.» — in Kauf nehmen bedeutet:",
     opts:["a) etwas kaufen","b) etwas als unvermeidbar akzeptieren","c) etwas ablehnen","d) etwas zurückgeben"],
     ans:"b) etwas als unvermeidbar akzeptieren",
     exp:"<strong>in Kauf nehmen</strong> = принимать (как неизбежное), мириться с чем-то. «Sie müssen die Nachteile <em>in Kauf nehmen</em>.» = вам придётся смириться с недостатками. Sehr häufig in Argumentationstexten!",
     rule:"IN KAUF NEHMEN = мириться с чем-то неизбежным (= akzeptieren müssen). C1!"},
    {n:10,
     aufgabe:"«Die Lösung kam ___ Anwendung.» — zur Anwendung kommen bedeutet:",
     opts:["a) Die Lösung wurde gesucht.",
           "b) Die Lösung wurde abgelehnt.",
           "c) Die Lösung wurde angewendet / eingesetzt.",
           "d) Die Lösung wurde diskutiert."],
     ans:"c) Die Lösung wurde angewendet / eingesetzt.",
     exp:"<strong>zur Anwendung kommen</strong> = применяться, использоваться. Passives Funktionsverbgefüge: statt «die Lösung wurde angewendet». Typisch für formelle/wissenschaftliche Texte C1.",
     rule:"ZUR ANWENDUNG KOMMEN = применяться (= angewendet werden). ZUR ANWENDUNG BRINGEN = применять."}
  ],
  vocab:["Funktionsverbgefüge — функциональный глагол (Nomen+Verb)","zur Verfügung stehen/stellen — быть в распоряжении / предоставлять","in Frage kommen — рассматриваться как вариант","in Frage stellen — ставить под сомнение","Bezug nehmen auf — ссылаться на","in Betracht ziehen — принимать во внимание","in Kraft setzen — вводить в действие","zum Ausdruck bringen — выражать","in Angriff nehmen — приступать к","in Kauf nehmen — мириться с (неизбежным)","zur Anwendung kommen — применяться"]
};
