// test-gr9.js — Grammatik: Temporalsatz & Adversativsatz
window.TELC_TEST = {
  id:"gr9", type:"Grammatik", kind:"gr",
  title:"Temporalsatz & Adversativsatz: sobald · seitdem · wohingegen",
  desc:"10 Aufgaben · Zeit & Gegensatz · C1",
  qs:[
    {n:1,
     aufgabe:"«___ er ankommt, rufe ich dich an.» — Unmittelbare Zeitfolge:",
     opts:["a) Nachdem","b) Sobald","c) Seitdem","d) Während"],
     ans:"b) Sobald",
     exp:"<strong>sobald</strong> = как только (немедленно после). «<em>Sobald</em> er ankommt, rufe ich dich an.» Unmittelbare Folge: Ereignis A → sofort B. <em>nachdem</em> = после того как (Reihenfolge, kein Betonung auf Unmittelbarkeit).",
     rule:"SOBALD = как только (немедленно). NACHDEM = после того как (Reihenfolge, Zeitversatz möglich)."},
    {n:2,
     aufgabe:"«___ er die Stelle angetreten hat, hat er viele Reformen eingeführt.» — Zeitraum seit Vergangenheit:",
     opts:["a) Sobald","b) Bevor","c) Seitdem","d) Bis"],
     ans:"c) Seitdem",
     exp:"<strong>seitdem</strong> = с тех пор как. «<em>Seitdem</em> er die Stelle angetreten hat, hat er viele Reformen eingeführt.» = с тех пор как он занял должность. Zeitraum von einem Punkt in der Vergangenheit bis jetzt.",
     rule:"SEITDEM = с тех пор как (от точки в прошлом до сейчас). Perfekt oder Präsens im Hauptsatz."},
    {n:3,
     aufgabe:"Unterschied: <em>nachdem</em> vs. <em>als</em> — wann wird welches verwendet?",
     opts:["a) Kein Unterschied — austauschbar.",
           "b) <em>nachdem</em> = Reihenfolge (Handlung A vor B); <em>als</em> = einmaliges Ereignis in der Vergangenheit.",
           "c) <em>als</em> = Zukunft; <em>nachdem</em> = Gegenwart.",
           "d) <em>nachdem</em> = gleichzeitig; <em>als</em> = nacheinander."],
     ans:"b) <em>nachdem</em> = Reihenfolge (Handlung A vor B); <em>als</em> = einmaliges Ereignis in der Vergangenheit.",
     exp:"<em>nachdem</em> = после того как (A geschah zuerst, dann B). <em>als</em> = когда (einmaliges Ereignis, Vergangenheit). <em>wenn</em> = когда (wiederholt oder Zukunft). Unterschied ist C1-Prüfungsthema!",
     rule:"ALS = когда (einmal, Vergangenheit). WENN = когда (wiederholt / Zukunft). NACHDEM = после того как."},
    {n:4,
     aufgabe:"«___ die Sitzung noch läuft, warte ich draußen.» — Gleichzeitigkeit:",
     opts:["a) Solange","b) Sobald","c) Seitdem","d) Nachdem"],
     ans:"a) Solange",
     exp:"<strong>solange</strong> = до тех пор, пока; пока (одновременность). «<em>Solange</em> die Sitzung läuft, warte ich.» = пока идёт заседание, я жду снаружи. Gleichzeitigkeit: beide Handlungen laufen parallel.",
     rule:"SOLANGE = пока (одновременно). SOBALD = как только (Übergang, Abfolge)."},
    {n:5,
     aufgabe:"«___ ich alles erklärt hatte, stellten sie Fragen.» — Zeitfolge Plusquamperfekt:",
     opts:["a) Als","b) Nachdem","c) Seitdem","d) Sobald"],
     ans:"b) Nachdem",
     exp:"<strong>nachdem + Plusquamperfekt</strong> = после того как (действие полностью завершено до следующего). «<em>Nachdem</em> ich alles erklärt <em>hatte</em>, stellten sie Fragen.» Regel: nachdem → Plusquamperfekt im Nebensatz, Präteritum im Hauptsatz.",
     rule:"NACHDEM + Plusquamperf. (hatte/war) → Hauptsatz Präteritum. Zeitversatz um eine Stufe!"},
    {n:6,
     aufgabe:"«Er liebt Großstädte, ___ seine Frau lieber auf dem Land lebt.» — Adversativ:",
     opts:["a) obwohl","b) wohingegen","c) sodass","d) damit"],
     ans:"b) wohingegen",
     exp:"<strong>wohingegen</strong> = тогда как, в то время как (противопоставление двух разных субъектов). «Er liebt Großstädte, <em>wohingegen</em> seine Frau lieber auf dem Land lebt.» Stärker als <em>während</em> bei Kontrast.",
     rule:"WOHINGEGEN = тогда как (контраст, разные субъекты). = während (adversativ), aber emphatischer."},
    {n:7,
     aufgabe:"«Er ist sehr optimistisch, ___ seine Kollegen eher pessimistisch sind.» — Welcher Konnektor?",
     opts:["a) wohingegen","b) während","c) beides korrekt","d) obwohl"],
     ans:"c) beides korrekt",
     exp:"<strong>während</strong> (adversativ) und <strong>wohingegen</strong> sind beide korrekt für Gegensatz zwischen zwei Sachverhalten. <em>wohingegen</em> betont den Kontrast stärker. <em>obwohl</em> wäre Konzessiv (zu einer Einschränkung), nicht einfacher Kontrast.",
     rule:"WÄHREND (adversativ) = в то время как. WOHINGEGEN = тогда как (сильнее). Beide: Nebensatz!"},
    {n:8,
     aufgabe:"«___ er sprach, nickte sie zustimmend.» — Gleichzeitigkeit (formal):",
     opts:["a) Als","b) Indem","c) Während","d) Sobald"],
     ans:"c) Während",
     exp:"<strong>während</strong> (temporal) = пока / в то время как (Gleichzeitigkeit). «<em>Während</em> er sprach, nickte sie.» = пока он говорил, она кивала. <em>indem</em> = способ действия (как именно), не просто одновременность.",
     rule:"WÄHREND (temporal) = пока / в то время как (Gleichzeitigkeit). ≠ während (adversativ, контраст)."},
    {n:9,
     aufgabe:"«___ der Termin nicht verschoben wird, können wir rechtzeitig fertig werden.» — Konditional mit Zeitbezug:",
     opts:["a) Solange","b) Sofern","c) Bevor","d) Bis"],
     ans:"b) Sofern",
     exp:"<strong>sofern</strong> = при условии, что. «<em>Sofern</em> der Termin nicht verschoben wird…» = при условии, что срок не перенесут. Hier ist es keine Zeit-, sondern eine Bedingungsangabe. <em>solange</em> wäre bei echter Gleichzeitigkeit.",
     rule:"SOFERN = при условии (Konditional). SOLANGE = пока (temporal/konditional gemischt)."},
    {n:10,
     aufgabe:"«Er arbeitete, ___ er völlig erschöpft war.» — Welcher Konnektor drückt Gleichzeitigkeit + Konzession?",
     opts:["a) während","b) obwohl","c) wohingegen","d) sobald"],
     ans:"b) obwohl",
     exp:"<strong>obwohl</strong> = хотя (Konzession). «Er arbeitete, <em>obwohl</em> er erschöpft war.» = он работал, хотя был совершенно истощён. <em>während</em> wäre nur Gleichzeitigkeit ohne Gegensatz. Die Kombination Gleichzeitigkeit + Gegensatz = Konzessiv.",
     rule:"OBWOHL = хотя (Konzession). WÄHREND (temporal) = пока (Gleichzeitigkeit). Bei Kontrast: obwohl."}
  ],
  vocab:["sobald — как только (немедленно)","seitdem — с тех пор как","nachdem — после того как","solange — пока (одновременно)","während — пока / в то время как (temporal); тогда как (adversativ)","wohingegen — тогда как (контраст)","als — когда (однократно, прошлое)","wenn — когда (многократно / будущее)","bis — до тех пор пока не","bevor — прежде чем"]
};
